//! Turn wrapped [`Strategy`]s into [`Strategy`]s generating wrapped values.

use proptest::prelude::*;
use std::fmt;

mod seal {
    pub trait Seal {}
}

/// Custom extension trait to turn wrapped [`Strategy`]s into [`Strategy`]s generating wrapped values.
///
/// In a sense, transposition pushes wrapping down into the values generated by [`Strategy`]s.
///
/// This trait is intentionally sealed and cannot be implemented by the user.
pub trait Transpose: seal::Seal {
    /// The strategy returned upon transposition.
    type Output;

    /// Transpose this [`Strategy`].
    fn transpose(self) -> Self::Output;
}

impl<S, T> seal::Seal for Option<S>
where
    S: Strategy<Value = T> + 'static,
    T: Clone + fmt::Debug + 'static,
{
}

impl<S, T> Transpose for Option<S>
where
    S: Strategy<Value = T> + 'static,
    T: Clone + fmt::Debug + 'static,
{
    type Output = BoxedStrategy<Option<T>>;

    fn transpose(self) -> Self::Output {
        match self {
            None => Just(None).boxed(),
            Some(s) => s.prop_map(Some).boxed(),
        }
    }
}
